#!/usr/bin/env python3
"""Generates seed_places.py from places_data.json"""
import json

with open('/Users/victorborisov/Projects/my/weekend-map/places_data.json', 'r') as f:
    places = json.load(f)

out = []
out.append("import os")
out.append("import time")
out.append("")
out.append("import requests")
out.append("from django.core.management.base import BaseCommand")
out.append("from django.conf import settings")
out.append("")
out.append("from places.models import CachedPlace")
out.append("")
out.append("")
out.append("def yandex_map_url(lat, lon, name):")
out.append("    import urllib.parse")
out.append("    return f'https://yandex.ru/maps/?ll={lon}%2C{lat}&z=15&text={urllib.parse.quote(name)}'")
out.append("")
out.append("")
out.append("def download_yandex_photo(lat, lon, osm_id):")
out.append("    media_dir = os.path.join(settings.MEDIA_ROOT, 'places')")
out.append("    os.makedirs(media_dir, exist_ok=True)")
out.append("    filepath = os.path.join(media_dir, f'{osm_id}.jpg')")
out.append("")
out.append("    if os.path.exists(filepath):")
out.append("        return f'/media/places/{osm_id}.jpg'")
out.append("")
out.append("    for z in [16, 15, 14]:")
out.append("        url = (")
out.append("            f'https://static-maps.yandex.ru/1.x/'")
out.append("            f'?ll={lon},{lat}&size=600,400&z={z}&l=sat'")
out.append("            f'&pt={lon},{lat},pm2rdm'")
out.append("        )")
out.append("        try:")
out.append("            resp = requests.get(url, timeout=30, headers={'User-Agent': 'weekend-map/1.0'})")
out.append("            if resp.status_code == 200 and len(resp.content) > 1000:")
out.append("                with open(filepath, 'wb') as f:")
out.append("                    f.write(resp.content)")
out.append("                return f'/media/places/{osm_id}.jpg'")
out.append("        except Exception:")
out.append("            pass")
out.append("        time.sleep(0.5)")
out.append("")
out.append("    return ''")
out.append("")
out.append("")
out.append("SEED_PLACES = [")

for p in places:
    out.append("    {")
    out.append(f"        'osm_id': {repr(p['osm_id'])},")
    out.append(f"        'name': {repr(p['name'])},")
    out.append(f"        'category': {repr(p['category'])},")
    out.append(f"        'lat': {p['lat']},")
    out.append(f"        'lon': {p['lon']},")
    desc = p['description']
    out.append(f"        'description': (")
    # Split description into ~120 char chunks
    while desc:
        chunk = desc[:120]
        desc = desc[120:]
        out.append(f"            {repr(chunk)}")
    out.append("        ),")
    tags_str = json.dumps(p['tags'], ensure_ascii=False)
    out.append(f"        'tags': {tags_str},")
    out.append("    },")

out.append("]")
out.append("")
out.append("")
out.append("class Command(BaseCommand):")
out.append("    help = 'Seed the database with curated weekend trip places in Leningrad Oblast'")
out.append("")
out.append("    def handle(self, *args, **options):")
out.append("        CachedPlace.objects.all().delete()")
out.append("        self.stdout.write(self.style.SUCCESS('Cleared existing places'))")
out.append("")
out.append("        for place in SEED_PLACES:")
out.append("            osm_id = place['osm_id']")
out.append("            lat = place['lat']")
out.append("            lon = place['lon']")
out.append("            name = place['name']")
out.append("")
out.append("            photo_path = download_yandex_photo(lat, lon, osm_id)")
out.append("            if photo_path:")
out.append("                place['photo_url'] = photo_path")
out.append("            else:")
out.append("                place['photo_url'] = ''")
out.append("")
out.append("            tags = place.get('tags', {})")
out.append("            tags['yandex_map_url'] = yandex_map_url(lat, lon, name)")
out.append("            place['tags'] = tags")
out.append("")
out.append("            obj = CachedPlace.objects.create(")
out.append("                osm_id=osm_id,")
out.append("                name=name,")
out.append("                category=place['category'],")
out.append("                lat=lat,")
out.append("                lon=lon,")
out.append("                description=place['description'],")
out.append("                tags=tags,")
out.append("                photo_url=place.get('photo_url', ''),")
out.append("            )")
out.append("            self.stdout.write(f'  Created: {name} (photo: {\"yes\" if photo_path else \"no\"})')")
out.append("")
out.append("        self.stdout.write(")
out.append("            self.style.SUCCESS(f'Seeded {len(SEED_PLACES)} places')")
out.append("        )")

content = '\n'.join(out) + '\n'

target = '/Users/victorborisov/Projects/my/weekend-map/backend/places/management/commands/seed_places.py'
with open(target, 'w') as f:
    f.write(content)

print(f"Generated {target} with {len(places)} places ({len(content)} bytes)")
