# Generated by Django 5.0.6 on 2026-09-26 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('category', models.CharField(choices=[('nature', 'Природа'), ('historic', 'Исторические места'), ('museum', 'Музеи'), ('viewpoint', 'Смотровые площадки'), ('tourism', 'Туризм'), ('leisure', 'Отдых и развлечения'), ('water', 'Водоёмы'), ('food', 'Еда и кафе')], default='tourism', max_length=32)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('description', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('photo_url', models.URLField(blank=True, default='', max_length=1024)),
                ('image', models.ImageField(blank=True, null=True, upload_to='places/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category'], name='places_cach_categor_2bf134_idx'), models.Index(fields=['lat', 'lon'], name='places_cach_lat_d07b66_idx')],
            },
        ),
        migrations.CreateModel(
            name='VisitedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, default='')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='places.cachedplace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visited_at'],
                'unique_together': {('user', 'place')},
            },
        ),
    ]
